/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb
*/
"use client";

import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import { useCallback, useEffect, useRef } from "react";

// The GLTF parent opts out of disposal to protect cached geometry and materials.
// These new materials belong to this mount; dispose only these, never their maps.
function OwnedMaterial({ kind: Material = "meshPhongMaterial", map, ...props }) {
  const ref = useRef(null);
  // The original MeshPhongMaterial constructor assigned this cached texture
  // directly. A JSX map prop makes R3F auto-convert it to sRGB, changing the room.
  // Assign it on update without mutating the texture's original color space.
  const bindMap = useCallback((material) => {
    if (map && material.map !== map) {
      material.map = map;
      material.needsUpdate = true;
    }
  }, [map]);
  useEffect(() => {
    const material = ref.current;
    return () => material?.dispose();
  }, []);
  return <Material ref={ref} {...props} onUpdate={bindMap} />;
}

export function Room(props) {
  const { nodes, materials } = useGLTF("/Models/optimized-room.glb");
  const screensRef = useRef();
  const matcapTexture = useTexture("/images/textures/mat1.png");

  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={0} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer>
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        >
        <OwnedMaterial color={"#d90429"} />
      </mesh>
      <mesh geometry={nodes.body1_blinn1_0.geometry} >
        <OwnedMaterial map={matcapTexture} />
      </mesh>
      <mesh geometry={nodes.cabin_blinn1_0.geometry} >
        <OwnedMaterial color={"#582f0e"} />
      </mesh>
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        >
        <OwnedMaterial color={"#000"} />
      </mesh>
      <mesh geometry={nodes.comp_blinn1_0.geometry} >
        <OwnedMaterial kind="meshStandardMaterial" color={"#fff"} />
      </mesh>
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        >
        <OwnedMaterial color={"#8338ec"} />
      </mesh>
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        >
        <OwnedMaterial color={"#fff"} />
      </mesh>
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh geometry={nodes.table_blinn1_0.geometry} >
        <OwnedMaterial color={"#582f0e"} />
      </mesh>
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/Models/optimized-room.glb");
